#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify OpenSSH config options are expected.
##     See
##     - https://github.com/openshift/os/pull/1251
##     - https://github.com/openshift/os/issues/1216
##     - https://issues.redhat.com/browse/OCPBUGS-11613

set -euo pipefail

. $KOLA_EXT_DATA/commonlib.sh

expected_opts=(
    "passwordauthentication no"
    "permitrootlogin no"
    "clientaliveinterval 180"
    "permitemptypasswords no"
    "strictmodes yes"
    "ignorerhosts yes"
    "ignoreuserknownhosts yes"
    "permituserenvironment no"
    "gssapiauthentication no"
    "printlastlog yes"
    "loglevel INFO"
)

for opt in "${expected_opts[@]}"; do
    key="${opt%% *}"
    if [[ "$(sshd -T | grep "^${key} ")" != "$opt" ]]; then
        fatal "${opt%% *} not set correctly, expected '${opt}'"
    fi
done
