#!/bin/bash
## kola:
##   # Since we pull a container image
##   tags: "needs-internet"
##   timeoutMin: 30
##   description: Verify that rhel8 journalctl can still read our journals.
##     https://issues.redhat.com/browse/OCPBUGS-11492

set -euo pipefail

. $KOLA_EXT_DATA/commonlib.sh

cd $(mktemp -d)

registry="registry.access.redhat.com"
type=$(podman image trust show --json | jq -r --arg reg "$registry" '.[] | select(.name == $reg) | .type')

if [ "$type" == "sigstoreSigned" ]; then
    source /etc/os-release
    if [ "$ID" == "centos" ]; then
        podman image trust set -t accept "$registry"
    elif [ "$ID" == "rhel" ]; then
        # See https://access.redhat.com/articles/3116561
        podman image trust set -f /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release "$registry"
        cat << EOF > /etc/containers/registries.d/${registry}.yaml
docker:
    ${registry}:
        sigstore: https://access.redhat.com/webassets/docker/content/sigstore
EOF
    else
        fatal "unknown $ID"
    fi
fi

# The string Linux should match the kernel boot
rc=0
podman run --privileged --net=none -v /var/log:/var/log:ro --rm registry.access.redhat.com/ubi8/ubi:latest journalctl -D /var/log/journal --grep="Linux" > journal.txt 2>err.txt || rc=$?
if [ "$rc" != 0 ]; then
    cat err.txt
    fatal "podman run exited with rc=$rc"
fi
if grep -qF 'uses an unsupported feature' err.txt; then
    fatal "Got unsupported feature trying to read journal"
fi
if ! grep -F "Linux" journal.txt; then
    fatal "Failed to read journal"
fi
