# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=centos
NAME=scos
STREAM=c9s
DESCRIPTION=CentOS Stream CoreOS 9
VERSION=9.0
MUTATE_OS_RELEASE=9
BUILDER_IMG=quay.io/centos-bootc/centos-bootc:stream9@sha256:eb4ee8ed4824fcf73c56af7b940c084e140e3827a384b9e090e12e2a4f107b8d
MANIFEST=manifest-c9s.yaml
IMAGE_CONFIG=image-c9s.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
