# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=rhel
NAME=rhcos
STREAM=rhel-10.2
DESCRIPTION=Red Hat Enterprise Linux CoreOS 10.2
VERSION=10.2
MUTATE_OS_RELEASE=10.2
BUILDER_IMG=registry.stage.redhat.io/rhel10/rhel-bootc:10.3@sha256:519d82cc1daebd4d260e740bc256a96078eeaeb712cfe46650911552896d380a
MANIFEST=manifest-rhel-10.2.yaml
IMAGE_CONFIG=image-rhel-10.2.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
