# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=rhel
NAME=rhcos
STREAM=rhel-10.2
DESCRIPTION=Red Hat Enterprise Linux CoreOS 10.2
VERSION=10.2
MUTATE_OS_RELEASE=10.2
BUILDER_IMG=registry.stage.redhat.io/rhel10/rhel-bootc:10.2@sha256:ab71b4141e26ba6e43308b492f396930e261b102c1385d33e71220d292d6a4c2
MANIFEST=manifest-rhel-10.2.yaml
IMAGE_CONFIG=image-rhel-10.2.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
