# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=rhel
NAME=rhcos
STREAM=rhel-10.2
DESCRIPTION=Red Hat Enterprise Linux CoreOS 10.2
VERSION=10.2
MUTATE_OS_RELEASE=10.2
BUILDER_IMG=registry.stage.redhat.io/rhel10/rhel-bootc:10.2@sha256:8f0da2429e107b3c483ba876341b307202726bbb3692dfd072637700c35225fd
MANIFEST=manifest-rhel-10.2.yaml
IMAGE_CONFIG=image-rhel-10.2.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
MAINTAINER=Red Hat
VENDOR=Red Hat, Inc.
URL=https://github.com/coreos/fedora-coreos-config
DISTRIBUTION_SCOPE=private
COMPONENT=rhel-coreos-10-2
# We use the same value as in openshift/os
# https://github.com/openshift/os/blob/62965e8043270be3ae4b4568f6f6475ed1804973/build-args-5.1-10.2.conf#L11
CPE_NAME=cpe:/a:redhat:openshift:5.1::el10
