# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=centos
NAME=scos
STREAM=c9s
DESCRIPTION=CentOS Stream CoreOS 9
VERSION=9.0
MUTATE_OS_RELEASE=9
BUILDER_IMG=quay.io/centos-bootc/centos-bootc:stream9@sha256:1372e13a5a8258bc3852ff2725f418a0c3b7d9e247d58c464065f46f883adea2
MANIFEST=manifest-c9s.yaml
IMAGE_CONFIG=image-c9s.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
