# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=rhel
NAME=rhcos
STREAM=rhel-9.8
DESCRIPTION=Red Hat Enterprise Linux CoreOS 9.8
VERSION=9.8
MUTATE_OS_RELEASE=9.8
BUILDER_IMG=registry.stage.redhat.io/rhel9/rhel-bootc:9.8@sha256:dc87f7b667c60741ab5e49629ea74d6ffd001a5f547f9597a9fc45acd20d1816
MANIFEST=manifest-rhel-9.8.yaml
IMAGE_CONFIG=image-rhel-9.8.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
MAINTAINER=Red Hat
VENDOR=Red Hat, Inc.
URL=https://github.com/coreos/rhel-coreos-config
DISTRIBUTION_SCOPE=private
COMPONENT=rhel-coreos-9-8
# We use the same value as in openshift/os
# https://github.com/openshift/os/blob/62965e8043270be3ae4b4568f6f6475ed1804973/build-args-5.1-10.2.conf#L11
CPE_NAME=cpe:/a:redhat:openshift:5.1::el9
