# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=centos
NAME=scos
STREAM=c10s
DESCRIPTION=CentOS Stream CoreOS 10
VERSION=10.0
MUTATE_OS_RELEASE=10
BUILDER_IMG=quay.io/centos-bootc/centos-bootc:stream10@sha256:0070da7e9bece3852df1abf0b0109f2a64fe325c22a6ca601788c02e969fcd10
MANIFEST=manifest-c10s.yaml
IMAGE_CONFIG=image-c10s.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
